---
global:
  gc: {{.GC}}
  gcMetrics: {{.GC_METRICS}}
  deletionStrategy: {{.DELETION_STRATEGY}}
  measurements:
    - name: podLatency
      thresholds:
        - conditionType: Ready
          metric: P99
          threshold: {{.POD_READY_THRESHOLD}}
    - name: autoNodeLatency
    - name: nodeClaimLatency

metricsEndpoints:
{{ if .ES_SERVER }}
  - metrics: [{{.METRICS}}]
    alerts: [{{.ALERTS}}]
    indexer:
      esServers: ["{{.ES_SERVER}}"]
      insecureSkipVerify: true
      defaultIndex: {{.ES_INDEX}}
      type: opensearch
{{ end }}
{{ if .LOCAL_INDEXING }}
  - metrics: [{{.METRICS}}]
    alerts: [{{.ALERTS}}]
    indexer:
      type: local
      metricsDirectory: collected-metrics-{{.UUID}}
{{ end }}

jobs:
  - name: autonode-scale
    namespace: autonode-test
    jobIterations: {{.JOB_ITERATIONS}}
    qps: {{.QPS}}
    burst: {{.BURST}}
    namespacedIterations: true
    churnConfig:
      cycles: {{.CHURN_CYCLES}}
      duration: {{.CHURN_DURATION}}
      percent: {{.CHURN_PERCENT}}
      delay: {{.CHURN_DELAY}}
      deleteDelay: {{.CHURN_DELETE_DELAY}}
      mode: {{.CHURN_MODE}}
    podWait: false
    waitWhenFinished: true
    preLoadImages: false
    jobPause: {{.JOB_PAUSE}}
    namespaceLabels:
      security.openshift.io/scc.podSecurityLabelSync: false
      pod-security.kubernetes.io/enforce: privileged
      pod-security.kubernetes.io/audit: privileged
      pod-security.kubernetes.io/warn: privileged
    jobIterationDelay: {{.WAVE_DELAY}}
    objects:
      - objectTemplate: deployment.yml
        replicas: 1
        inputVars:
          cpuRequests: {{.CPU_REQUESTS | toJson}}
          nodepools: {{.NODEPOOLS | toJson}}
          podCounts: {{.POD_COUNTS | toJson}}
          containerImage: {{.CONTAINER_IMAGE}}
{{ if gt .STRESS_SECRETS 0 }}
      - objectTemplate: secret.yml
        replicas: {{.STRESS_SECRETS}}
{{ end }}
{{ if gt .STRESS_CONFIGMAPS 0 }}
      - objectTemplate: configmap.yml
        replicas: {{.STRESS_CONFIGMAPS}}
{{ end }}
{{ if gt .STRESS_SERVICES 0 }}
      - objectTemplate: service.yml
        replicas: {{.STRESS_SERVICES}}
{{ end }}
{{ if gt .STRESS_ROUTES 0 }}
      - objectTemplate: route.yml
        replicas: {{.STRESS_ROUTES}}
{{ end }}
{{ if gt .STRESS_NETWORKPOLICIES 0 }}
      - objectTemplate: np-deny-all.yml
        replicas: 1
      - objectTemplate: np-allow-from-ingress.yml
        replicas: 1
{{ end }}
