apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.JobName}}-{{.Replica}}-{{.Iteration}}
  labels:
    app: autonode-pause
spec:
  replicas: {{ index .podCounts .Iteration }}
  selector:
    matchLabels:
      instance: {{.JobName}}-{{.Replica}}-{{.Iteration}}
  template:
    metadata:
      labels:
        app: autonode-pause
        instance: {{.JobName}}-{{.Replica}}-{{.Iteration}}
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: pause
          image: {{.containerImage}}
          resources:
            requests:
              cpu: {{ index .cpuRequests .Iteration }}
              memory: {{.memoryRequest}}
          imagePullPolicy: IfNotPresent
