apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.JobName}}-{{.Replica}}
  labels:
    app: autonode-pause
spec:
  replicas: {{ index .podCounts .Iteration }}
  selector:
    matchLabels:
      instance: {{.JobName}}-{{.Replica}}
  template:
    metadata:
      labels:
        app: autonode-pause
        instance: {{.JobName}}-{{.Replica}}
    spec:
      terminationGracePeriodSeconds: 0
      {{- $np := index .nodepools .Iteration }}
      {{- if $np }}
      nodeSelector:
        karpenter.sh/nodepool: "{{ $np }}"
      {{- end }}
      containers:
        - name: pause
          image: {{.containerImage}}
          command: ["sleep", "inf"]
          resources:
            requests:
              cpu: {{ index .cpuRequests .Iteration }}
          imagePullPolicy: IfNotPresent
          readinessProbe:
            exec:
              command: ["/bin/sh", "-c", "true"]
            initialDelaySeconds: 1
            periodSeconds: 10
          livenessProbe:
            exec:
              command: ["/bin/sh", "-c", "true"]
            initialDelaySeconds: 5
            periodSeconds: 30
