---
kind: Service
apiVersion: v1
metadata:
  name: {{.JobName}}-svc-{{.Replica}}
spec:
  selector:
    app: autonode-pause
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP
