---
global:
  gc: {{.GC}}
  gcMetrics: {{.GC_METRICS}}
  measurements:
    - name: nthSpotLatency
    - name: machineLatency

metricsEndpoints:
{{ if .ES_SERVER }}
  - metrics: [{{.METRICS}}]
    alerts: [{{.ALERTS}}]
    indexer:
      esServers: ["{{.ES_SERVER}}"]
      insecureSkipVerify: true
      defaultIndex: {{.ES_INDEX}}
      type: opensearch
{{ end }}
{{ if .LOCAL_INDEXING }}
  - metrics: [{{.METRICS}}]
    alerts: [{{.ALERTS}}]
    indexer:
      type: local
      metricsDirectory: collected-metrics-{{.UUID}}
{{ end }}

jobs:
  - name: nth-spot-observe
    namespace: nth-observe
    jobIterations: 1
    qps: {{.QPS}}
    burst: {{.BURST}}
    cleanup: true
    podWait: false
    waitWhenFinished: true
    preLoadImages: false
    metricsClosing: afterMeasurements
    namespaceLabels:
      security.openshift.io/scc.podSecurityLabelSync: false
      pod-security.kubernetes.io/enforce: privileged
      pod-security.kubernetes.io/audit: privileged
      pod-security.kubernetes.io/warn: privileged
    objects: []
